version: '3.8'

services:

  db:
    image: postgres:12.3
    environment:
      POSTGRES_USER: blog_admin
      POSTGRES_PASSWORD: something
      POSTGRES_DB: blog
    volumes:
      - ./.data/pgdata:/var/lib/postgresql/data

  server:
    image: jindodog/blog-server
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/blog"
      SPRING_DATASOURCE_USERNAME: "blog_admin"
      SPRING_DATASOURCE_PASSWORD: "something"
