version: '3.8'

services:

  db:
    image: postgres:12.3
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: blog_admin
      POSTGRES_PASSWORD: something
      POSTGRES_DB: blog
    volumes:
      - ./.data/pgdata:/var/lib/postgresql/data

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - ./.data/esdata:/usr/share/elasticsearch/data
