version: '3.0'

services:

  server:
    image: jindodog/blog-server:latest
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/blog"
      SPRING_DATASOURCE_USERNAME: blog_admin
      SPRING_DATASOURCE_PASSWORD: something
      SPRING_PROFILES_ACTIVE: data,prod

  db:
    image: postgres:12.3
    environment:
      POSTGRES_USER: blog_admin
      POSTGRES_PASSWORD: something
      POSTGRES_DB: blog
    volumes:
      - /opt/docker-data/blog/main:/var/lib/postgresql/data
