spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/blog"
    username: blog_admin
    password: something
    driver-class-name: org.postgresql.Driver

---
spring:
  profiles: test
  name: test-YAML
  jpa:
    hibernate:
      ddl-auto: create
logging:
  level:
    org:
      springframework:
        web:
          servlet:
            DispatcherServlet: DEBUG

---
spring:
  profiles: dev
  name: dev-YAML
  jpa:
    hibernate:
      ddl-auto: create
logging:
  level:
    org:
      springframework:
        web:
          servlet:
            DispatcherServlet: DEBUG

---
spring:
  profiles: prod
  name: production-YAML
  jpa:
    hibernate:
      ddl-auto: update
